fix: only escape key/values for data in POST requests.
coreruleset/go-ftw pull request #103
Opened 2022-11-11 05:02 UTC by anuraaga

When trying to update FTW, I noticed CRS tests passing and AFAICT, it is because of the escaping behavior introduced in #96. Now, there are never key/value pairs since equals and ampersands are always escaped. Ideally, the test format itself was a yaml map instead of a single string, but as is now, I think we have to assume that `=` and `&` in the `data` field are the form parameter delimiters and only escape the actual key/values.

2022-11-11 07:17 UTC, theseion requested changes
Thanks for the effort. We need to clean this up properly at some point. For example, I think we need to be able to control:
- space endoding (`%20` or `+`)
- parameter encoding (`=`, `&`) since the current encoding format is just a convention

We should also properly separate encoding of the query string and post body data.

2022-11-11 07:17 UTC, theseion commented on ftwhttp/request_test.go
> +			encoded: "foo+bar",
Add another that includes ampersand.

2022-11-11 12:22 UTC, fzipi approved these changes

2022-11-11 17:32 UTC, theseion approved these changes

2022-11-12 00:49 UTC, merged

2022-11-12 00:49 UTC, jcchavezs approved these changes