fix: no longer negate `autocomplete_headers` option
coreruleset/go-ftw pull request #176
Opened 2023-08-07 13:17 UTC by theseion

When the logic was inverted, as we renamed `stop_magic` to `autocomplete_headers`, we forgot to remove the logic inversion when passing the option to the request builder.

2023-08-07 21:11 UTC, fzipi requested changes
I would say let's write a test to catch this?

2023-08-08 18:17 UTC, theseion commented
Yes... I was being lazy and you caught me 😅.

2023-08-21 19:00 UTC, theseion commented
Should be good now.

2023-08-23 12:31 UTC, fzipi approved these changes

2023-08-23 12:31 UTC, merged