Overhaul README.md
coreruleset/go-ftw pull request #98
Opened 2022-10-30 17:51 UTC by dune73

2022-11-11 12:31 UTC, fzipi requested changes
Looks good. For consistency, we need to make changes in additional places probably.

2022-11-11 12:31 UTC, fzipi commented on README.md
> +* `logmarkerheadername` : name of a HTTP header used for marking log messages, usually `X-CRS-TEST` (see section "How log parsing works" below)
```suggestion
* `logmarkerheadername` : name of a HTTP header used for marking log messages, usually `X-CRS-TEST` (see [How log parsing works](https://github.com/coreruleset/go-ftw#how-log-parsing-works) below)
```

2022-11-11 12:31 UTC, fzipi commented on README.md
> +3. go-ftw config file `.ftw.yaml` in the local folder or in your home folder (see section "YAML Config file" for more information.
```suggestion
3. go-ftw config file `.ftw.yaml` in the local folder or in your home folder (see [YAML Config file](https://github.com/coreruleset/go-ftw#yaml-config-file) for more information).
```

2022-11-11 12:31 UTC, fzipi commented on README.md
> +mode: "default"
Maybe we want to add more examples:
- this has mostly everything set, with the logfile being absolute
- add a relative logfile example
- add a minimal config: the bare minimum needed is the `logfile`.

2022-11-11 12:31 UTC, fzipi commented on README.md
> +  "id:900910,\
If you change it here, you need probably to change it all over the place. In particular, [here](https://github.com/coreruleset/modsecurity-crs-docker/blob/b0603c1832a38eb578eefce462218f367af7c88e/src/opt/modsecurity/activate-rules.sh#L133)

2022-11-11 23:10 UTC, dune73 commented
Thank you @fzipi. I think I have covered all your comments.

I'm not a fan of rule ID 999999. But it's not necessary to start to change a lot of things all of a sudden.

2022-11-12 17:05 UTC, fzipi approved these changes

2022-11-12 17:05 UTC, merged